const RaidersObj = {
  Santo: {
    user: 'Santo',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/224/173798880-main.jpg',
    class: 'Warlock',
    classimg: '../assets/png/dk.png',
  },
  Serrow: {
    user: 'Serrow',
    class: 'Druid',
    spec: 'Balance',
    small: 'https://render-us.worldofwarcraft.com/character/malganis/173/178962861-avatar.jpg',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/173/178962861-main.jpg',
    classimg: '../assets/png/dk.png',
  },
  Ethren: {
    user: 'Ethren',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/195/180125635-main.jpg',
    class: 'Demon Hunter',
    classimg: '../assets/png/dk.png',
  },
  Ryanlockwood: {
    user: 'Ryanlockwood',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/233/153922281-main.jpg',
    class: 'Paladin',
    classimg: '../assets/png/dk.png',
  },
  Neon: {
    user: 'Neon',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Death Knight',
    classimg: '../assets/png/dk.png',
  },
  Nysti: {
    user: 'Nysti',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Death Knight',
    classimg: '../assets/png/monk.png',
  },
  Goonda: {
    user: 'Goonda',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/224/173798880-main.jpg',
    class: 'Priest',
    classimg: '../assets/png/priest.png',
  },
  Cut: {
    user: 'Cut',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/195/180125635-main.jpg',
    class: 'Monk',
    classimg: '../assets/png/monk.png',
  },
  Sab: {
    user: 'Sabnoc',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/233/153922281-main.jpg',
    class: 'Demon Hunter',
    classimg: '../assets/png/dh.png',
  },
  Andyj: {
    user: 'Andyj',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Hunter',
    classimg: '../assets/png/hunter.png',
  },
  Mymind: {
    user: 'Mymind',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Mage',
    classimg: '../assets/png/mage.png',
  },
  Doc: {
    user: 'Docit',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/233/153922281-main.jpg',
    class: 'Warlock',
    classimg: '../assets/png/warlock.png',
  },
  Eevee: {
    user: 'Eevee',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Monk',
    classimg: '../assets/png/monk.png',
  },
  Imperator: {
    user: 'Imperator',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Death Knight',
    classimg: '../assets/png/dk.png',
  },
  Clout: {
    user: 'Cloutchocula',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Hunter',
    classimg: '../assets/png/hunter.png',
  },
  Xoff: {
    user: 'Xcff',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Mage',
    classimg: '../assets/png/mage.png',
  },
  Necro: {
    user: 'Necrox',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Death Knight',
    classimg: '../assets/png/dk.png',
  },
  Mar: {
    user: 'Mar',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Rogue',
    classimg: '../assets/png/rogue.png',
  },
  Jarcce: {
    user: 'Jarcce',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Mage',
    classimg: '../assets/png/mage.png',
  },
  Blazy: {
    user: 'Blazybear',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Warlock',
    classimg: '../assets/png/warlock.png',
  },
  Vahyair: {
    user: 'Vahyair',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Rogue',
    classimg: '../assets/png/rogue.png',
  },
  Ezpied: {
    user: 'Ezpied',
    large: 'https://render-us.worldofwarcraft.com/character/malganis/223/180819679-main.jpg',
    class: 'Hunter',
    classimg: '../assets/png/hunter.png',
  },
};

export default { RaidersObj };
